INPUT:
  MIN_DIM: 736
  MAX_DIM: 1792
  NUM_CLASSES: 19
  NUM_FRAMES: 8
  IMAGE_MEAN: [0.485, 0.456, 0.406] # [102.9801, 115.9465, 122.7717]
  IMAGE_STD: [0.229, 0.224, 0.225] # [1.0, 1.0, 1.0]
  NORMALIZE_TO_UNIT_SCALE: True
MODEL:
  EMBEDDING_DIM_MODE: "xyt"
  USE_SEEDINESS_HEAD: false
  USE_SEMSEG_HEAD: true
TRAINING:
  MODE: "kitti_step"
  INITIAL_LR: 0.001
  LR_DECAY_TYPE: "none"
  MAX_ITERATIONS: 20000
CLUSTERING:
  MIN_SEEDINESS_PROB: 0.95
DATA:
  KITTI_STEP:
    MAPILLARY_WEIGHT: 0.0
    KITTI_STEP_WEIGHT: 1.0